development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myflix_development
  pool: 5
  username: myflix
  password: myflix

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: myflix_test
  pool: 5
  username: myflix
  password: myflix

production:
  adapter: postgresql
  encoding: unicode
  pool: 5