development:
  secret_token: 5ca092daf2d0d70708d5f56d46fa1b055bcbc461a78b481e04722758c5fc120c918b84600f3396edceef8e79bcefab345d89f7763be2c7001781aab33193acd6
  secret_key_base: 5ca092daf2d0d70708d5f56d46fa1b055bcbc461a78b481e04722758c5fc120c918b84600f3396edceef8e79bcefab345d89f7763be2c7001781aab33193acd6
  mail_username: mailer@myflix.at
  mail_password: myflix
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>

test:
  secret_token: 5ca092daf2d0d70708d5f56d46fa1b055bcbc461a78b481e04722758c5fc120c918b84600f3396edceef8e79bcefab345d89f7763be2c7001781aab33193acd6
  secret_key_base: 5ca092daf2d0d70708d5f56d46fa1b055bcbc461a78b481e04722758c5fc120c918b84600f3396edceef8e79bcefab345d89f7763be2c7001781aab33193acd6
  mail_username: mailer@myflix.at
  mail_password: myflix
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>

staging:
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mail_username: <%= ENV['MAIL_USERNAME'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_api_key: <%= ENV['MAIL_API_KEY'] %>
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  mail_recipient: <%= ENV['MAIL_RECIPIENT'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>

production:
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  mail_username: <%= ENV['MAIL_USERNAME'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_api_key: <%= ENV['MAIL_API_KEY'] %>
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  sentry_api_key: <%= ENV['SENTRY_API_KEY'] %>
  s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>